find_package(GTest REQUIRED CONFIG)
set(TARGET_NAME distributed_knapsack)
set(UT_TARGET_NAME "distributed_knapsack_tests")
file(GLOB TEST_SOURCES  *.cpp *c )
get_target_property(TGT_INCLUDE_DIRS ${TARGET_NAME} INCLUDE_DIRECTORIES)
get_target_property(TGT_LIBRARIES ${TARGET_NAME} LINK_LIBRARIES)
get_target_property(SRC_LIST ${TARGET_NAME} SOURCES)
list(FILTER SRC_LIST EXCLUDE REGEX ".*main.*")
add_executable(${UT_TARGET_NAME} ${TEST_SOURCES} ${SRC_LIST})
target_include_directories(${UT_TARGET_NAME} PUBLIC ${TGT_INCLUDE_DIRS})
target_link_libraries(${UT_TARGET_NAME} PUBLIC ${TGT_LIBRARIES} PRIVATE GTest::gtest GTest::gtest_main tasker fmt::fmt)
add_subdirectory(mpi)