
class KnapsackSolution:
    def __init__(self, totalValue: int, totalWeight: int):
        self.totalValue = totalValue
        self.totalWeight = totalWeight

class KnapsackArguments:
    def __init__(self, weights: list[int], values: list[int], capacity: int):
        self.weights = weights
        self.values = values
        self.capacity = capacity

def knapsackdp(args: KnapsackArguments, numThreads: int = 1) -> KnapsackSolution: ...
def knapsackcopa(args: KnapsackArguments, numThreads: int = 1) -> KnapsackSolution: ...
def knapsackcopasequential(args: KnapsackArguments) -> KnapsackSolution: ...
def knapsackcopampi(args: KnapsackArguments) -> KnapsackSolution: ...
def knapsackdpmpi(args: KnapsackArguments) -> KnapsackSolution: ...
def disable_logging() -> None: ...