def hello() -> None: ...

class KnapsackSolution:
    def __init__(self, items: list[int] = [], totalValue: int = 0, totalWeight: int = 0): ...
    items: list[int]
    totalValue: int
    totalWeight: int

class KnapsackArguments:
    def __init__(self, weights: list[int], values: list[int], capacity: int): ...
    weights: list[int]
    values: list[int]
    capacity: int

def knapsackdp(args: KnapsackArguments) -> KnapsackSolution: ...
def knapsackcopa(args: KnapsackArguments) -> KnapsackSolution: ...
def knapsackcopasequential(args: KnapsackArguments) -> KnapsackSolution: ...
def knapsackdpdag(args: KnapsackArguments, item_block: int = 10, cap_block: int = 0) -> KnapsackSolution: ...
def disable_logging() -> None: ...

class TimeSection:
    min: float
    max: float
    mean: float
    variance: float
    count: int

def get_section(name: str) -> TimeSection: ...
def get_all_sections() -> dict[str, TimeSection]: ...
